name = "roadcdn"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "roadcdn-cache"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "roadcdn-assets"

[vars]
DEFAULT_TTL = "86400"
MAX_AGE = "31536000"
